export {default as Section} from './Section'
export {default as Header} from './Header/Header'
export {default as Hero} from './Hero/Hero'
export {default as Skills} from './Skills/Skills'
export {default as Projects} from './Projects/Projects'
export {default as About} from './About/About'
export {default as CTA} from './CTA/CTA'
export {default as Contact} from './Contact/Contact'